version: "3.8"
services:
  mongodbForex:
    image: docker.io/bitnami/mongodb:latest
    restart:
      on-failure
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_forex_data:/bitnami/mongodb'
    networks:
      - network

  fx-back:
    image: docker.inowa.it/fx/fx-back
    build:
      context: .
      dockerfile: Dockerfile
    restart:
      on-failure
    ports:
      - "8000:8000"
    container_name:
      "fx-back"
    networks:
      - network

  fx-front:
    image: docker.inowa.it/fx/fx-front
    build:
      context: .
      dockerfile: Dockerfile
    restart:
      on-failure
    ports:
      - "3000:3000"
    container_name:
      "fx-front"
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  mongodb_forex_data:
    driver: local
